# Generated by Django 2.1.5 on 2019-01-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.TextField()),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('comp', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.users'),
        ),
    ]
